# Generated by Django 4.2.5 on 2023-10-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_code_verification_user_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-is_superuser', '-is_staff'), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
