# Generated by Django 4.2.5 on 2023-10-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержимое')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Фото')),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('created_date',),
            },
        ),
    ]
