# Generated by Django 4.2.5 on 2023-10-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_send_mail', '0004_alter_logs_attempt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='attempt_status',
            field=models.CharField(choices=[('OK', 'Успешно'), ('ERROR', 'Ошибка')], default='OK', max_length=20, verbose_name='Статус отправки'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='send_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время отправки'),
        ),
    ]
